package tests_day_7

import "../../src/day_7"

import "core:testing"

@(test)
part_1_test_1 :: proc(t: ^testing.T) {
	test_input := `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`
	test_input = test_input[1:]
	res := day_7.sol_part_1(test_input)

	testing.expect_value(t, res, 21)
}

@(test)
part_1_test_2 :: proc(t: ^testing.T) {
	test_input := `
...S...
.......
...^...
.......
..^.^..
.......
`
	test_input = test_input[1:]
	res := day_7.sol_part_1(test_input)

	testing.expect_value(t, res, 3)
}

@(test)
part_2_test_1 :: proc(t: ^testing.T) {
	test_input := `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`
	test_input = test_input[1:]
	res := day_7.sol_part_2(test_input)

	testing.expect_value(t, res, 40)
}

@(test)
part_2_test_2 :: proc(t: ^testing.T) {
	test_input := `
...S...
.......
...^...
.......
..^.^..
.......
`
	test_input = test_input[1:]
	res := day_7.sol_part_2(test_input)

	testing.expect_value(t, res, 4)
}
